apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    component: user
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      environment: dev
      component: user
  template:
    metadata:
      labels:
        project: roboshop
        environment: dev
        component: user
    spec:
      containers:
      - name: user
        image: "{{ .Values.deployment.imageVersion }}"
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:   
  name: user
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    component: user
spec:
  selector:
    project: roboshop
    environment: dev
    component: user
  ports:
    - protocol: TCP
      port: {{ .Values.service.servicePort }} #Service port
      targetPort: 8080      #container port
  


    
          

