apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    component: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      environment: dev
      component: redis
  template:
    metadata:
      labels:
        project: roboshop
        environment: dev
        component: redis
    spec:
      containers:
      - name: redis
        image: "{{ .Values.deployment.imageRepo }}"
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 15
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    component: redis
spec:
  selector:
    project: roboshop
    environment: dev
    component: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
  labels:
     project: roboshop
     environment: dev
     component: redis
spec:
  selector:
    project: roboshop
    environment: dev
    component: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379  
  
  