apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue
  namespace: roboshop
data:
  MONGO: "true"
  MONGO_URL: {{ .Values.configmap.mongoURL }}
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    component: catalogue
spec:
  replicas: 2
  selector:
    matchLabels:
      project: roboshop
      environment: dev
      component: catalogue
  template:
    metadata:
      project: roboshop
      environment: dev
      component: catalogue
  spec:
    containers:
    - name: catalogue
      image: "{{ .Values.deployment.imageVersion }}"
      imagePullPolicy: Always
      readinessProbe:
       tcpSocket:
        port: 27017
       initialDelaySeconds: 15
       periodSeconds: 10
      livenessProbe:
        tcpSocket:
         port: 27017
        initialDelaySeconds: 15
        periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:   
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    component: catalogue
spec:
  selector:
    project: roboshop
    environment: dev
    component: catalogue
  ports:
    - protocol: TCP
      port: {{ .Values.service.servicePort }} #Service port
      targetPort: 8080      #container port
  


    
          

